language: node_js
node_js:
- node
script: grunt build
deploy:
  provider: s3
  access_key_id: AKIAJP4O7XR4OBMSDI6A
  secret_access_key:
    secure: kj2M0Ek+/kePP8M3yGmWrqDF4BYsjlA/fHqIx9BYIcE7POG4U5TP2ohT2ewiopBN9Wv5hRPKmkRjBPjC4glqstYJfZJ+l6BXDX+KkokuRwejVayLJayPptv2Jgp5C5zz39kH/uaLNkpaOZl3HVx4UtElj2fT54uk+X4oZZ+fDM1C7oxiwQk7ewQy5R99EJXdZgktRa2mzhhOoNZZ3Z5V/3Q/02Du4+gOpm5q70ApGsf6XLkaniFlkC3EtFFPwcyqq1fmk4Ld9SnI4WSTgkset6ITguvwvKlgaTUYoitHyGsHsWGriFVmNkpIhi2Gnugs/k2MJ/owMHLmXLezQiK+KmumK4cMVutrzoCH/ZGjbfv5RFG7NDnXOaPvE4Uus0/gOxbjUWZQREIjuslKiLm6jZQyzcOrh1YKbzviFjs5fqY+DJBvMJlpOpAAu2wRK4e+KFGWETZxCz/6V1odFLa3F3rPl2nr13i/cy9Db3QLiGAJpsn/gX7D6eNHNumNF8Jk2NVCwWvCpT0YvAH2mdCaHR0RCq/HHwr6hw/wFmOq48VmnK2pssv7JyAs7vWqvZMymnwrGRY68Wt2YE4FoOLZuV6nrGnYST0x5aamVWSagw18T8w9iOhuTMr6dLcxwfvotTeUxJmQD8ItRmFKTdr5ortyJhx1ePhtOaNHnJb9ADU=
  bucket: www.tomacfamily.com
  local-dir: dist
  on:
    repo: rtomac/tomacfamily.com
  skip_cleanup: true