language: node_js
node_js:
- node
script: grunt build
deploy:
  provider: s3
  access_key_id: AKIA4EHLXLC5SQYBKHNL
  secret_access_key:
    secure: QAc9sN8/Pixq9S0Pd9fRwHVQya5MXKOypZp0I1/NU38MejICr/VaeVEBOCSEkmiD1wtgRfUkfmoef+zQM2aIYwY2YTRvM9nTlNigzl/eVQ8ker/Zgu/3U2Oy/bhXV3JS5cvco5esYqyPMKYP0vj5imyBg4pIjAT2W+wITINMBFozlXN1aJD4fBv4UmrSHxnSIrvHtYYE7peDmAvo3TA594OiEFFR1v9nC2VFvnckjjtQmqR9WJ/A2lXGBmM4q1FhSa/GIlvUobnBosI8Kadymqs7ETAcaA5w/3X5dK+XcMpdtHg05jOHmSqaoPCtflCspFvMUHI8KMVlOixGIhMmzW8v+UN0C42+HerZQhkzk+DRsKIpAR75IKR9c5FsWqS/2dzTpBnOV0Q9uUXMFJYc3jGxEhYJ7sRoUiMKduPwXeIZOx46BoprN+3hkx0qGEeGDkCTQKWd9M9d0Fn0R0FDoN/3qRbwTZ8TIy9jwarrvifemNHXdSMglbLhT2uca6pJe9Xx5sR/4YHEmQRxWPGZCdqZ38IpXfwxv15peMrKo7XxBP0Npw3vuxPMLufBjRl+ecTNwzSHHnMGT2qPxwhqiMC4OaSysEgvkx9DTlr5ardMXkcna9WoeaEiGQuOy5083CECfqmoyG3XkI13ltfefZTf0bdmracJHKJNiM4UsPw=
  bucket: tomacfamily.com
  region: us-west-2
  local-dir: dist
  on:
    repo: rtomac/tomacfamily.com
  skip_cleanup: true
